version: '3.9'

services:
  l2:
    extends:
      file: ./services/op-geth.yml
      service: l2

  op-node:
    depends_on:
      - l2
    extends:
      file: ./services/op-node.yml
      service: op-node






