version: '3.9'

services:
  l2:
    image: rss3/op-geth:latest
    pull_policy: always
    platform: linux/amd64
    ports:
      - "8545:8545"
      - "7300:7300"
    volumes:
      - "./l2_data:/db"
      - "../config/genesis.json:/config/genesis.json"
      - "../config/jwt-secret.txt:/config/jwt-secret.txt"
      - "../entrypoint-l2.sh:/entrypoint.sh"
    entrypoint:
      - "/bin/sh"
      - "/entrypoint.sh"
    container_name: 'op-geth-l2'
    env_file:
      - ../envs/op-geth.env
