version: '3.9'

services:
  op-node:
    image: rss3/op-node:6ab6190a6eb5694dca0887cb7ecc5013ea238a31
    pull_policy: always
    platform: linux/amd64
    container_name: 'op-node'
    ports:
      - "9545:9545"
      - "9003:9003"
      - "6061:6061"
      - "7301:7301"
    volumes:
      - "../${NETWORK}/opnode_p2p_priv.txt:/config/opnode_p2p_priv.txt"
      - "../${NETWORK}/jwt-secret.txt:/config/jwt-secret.txt"
      - "../${NETWORK}/rollup.json:/config/rollup.json"
      - ./op_log:/op_log

    env_file:
      - ../.env
      - op-node.env
      - ../${NETWORK}/.config
